language: minimal
deploy:
  provider: script
  skip_cleanup: true
  script: bash deployment/deploy.sh
  on:
    branch: master
addons:
  ssh_known_hosts: raeder.technology
before_deploy:
  - openssl aes-256-cbc -K $encrypted_77afa1d090a3_key -iv $encrypted_77afa1d090a3_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa